In [2]:
#importacion de librerias#
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

In [3]:
#cargamos datos#
np.random.seed(0)
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
#añadimos nuevas columnaa de dimencion de las especies#
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
#mostramos las 5 primeras columnas#
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [5]:
#crear enrenamiento y datos de prueva#
#crear nueva columna de manera aleatoria entre 0 y 1#
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [6]:
#creacion de dos data frame uno de training y test#
train, test = df[df['is_train'] == True], df[df['is_train'] == False]

In [7]:
#mostramos los numeros a observa en el test y training#

print('numero de obserbaciones en los datos entrenamiento: ', len(train))
print('numero de obserbaciones en los datos de test: ', len(test))

numero de obserbaciones en los datos entrenamiento:  118
numero de obserbaciones en los datos de test:  32


In [8]:
#creacion de lista de feature con combres de la columna#
features = df.columns[:4]

#visualizamos la lista#
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [9]:
#entrenamiento con especies convirtiendo cada una en digito 0, 1 o 1#
y = pd.factorize(train['species'])[0]

#visualisamos la entidad#
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [10]:
#crear el arbol de decicion aleatoria por convencion, nombre#
clf = RandomForestClassifier(n_jobs = 2, random_state = 0)

#aprendisaje con los valores de entrenamiento#
clf.fit(train[features], y)

C:\Users\Jonathan B M\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [11]:
#####aplicar clasificador a datos de prueva####
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [13]:
#visualizar la prediccion de las priemras 10 observaciones#
clf.predict_proba(test[features])[0:10]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [14]:
####evaluar el clasificados####
#crear el nombre actual en ingles de las platas para predecir la clase#
preds = iris.target_names[clf.predict(test[features])]


#visualizar la prediccion#
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [15]:
#visualizar las especies actuales para la primeras 5 observaciones#
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [16]:
####Crear una matris de confucion####
pd.crosstab(test['species'], preds, rownames = ['Actual Species'], colnames = ['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

In [17]:
#ver la importancia de la caracteristica#
list(zip(train[features], clf.feature_importances_))

[('sepal length (cm)', 0.11185992930506346),
 ('sepal width (cm)', 0.016341813006098178),
 ('petal length (cm)', 0.36439533040889194),
 ('petal width (cm)', 0.5074029272799464)]